spring:
  datasource: 
    url: jdbc:postgresql://localhost:5432/gestionart
    username: postgres
    password: luis1994
  messages:
    basename: Messages
    encoding: UTF-8
  thymeleaf:
    encoding: UTF-8
  jpa: 
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
        
server:
  servlet:
    context-path: /gestionart